/* ============================================================================
 * GENERATED by tools/gen_schema.py from schema/plume.schema.json —— 请勿手改。
 * 改动改 schema 后重跑生成器；CTest `schema_gen_drift` 会校验产物与 schema 一致。
 * ==========================================================================*/
#include <plume/plume_ui_gen.h>
#include <plume/plume_kernel.h>
#include "schema/plume_schema_gen.h"

static void pl_ui_gen_add_children(PlNode parent, PlNode* kids) {
    for (int i = 0; i < PL_GEN_MAX_CHILDREN && kids[i]; ++i) pl_add_child(parent, kids[i]);
}

PlNode pl_box(PlCtx ctx, PlBoxDesc d) {
    PlNode n = pl_make(ctx, "pl.Box");
    if (d.width != 0) pl_node_set_len(n, kPlProp_Width, pl_px(d.width));
    if (d.height != 0) pl_node_set_len(n, kPlProp_Height, pl_px(d.height));
    if (d.min_width != 0) pl_node_set_len(n, kPlProp_MinWidth, pl_px(d.min_width));
    if (d.min_height != 0) pl_node_set_len(n, kPlProp_MinHeight, pl_px(d.min_height));
    if (d.max_width != 0) pl_node_set_len(n, kPlProp_MaxWidth, pl_px(d.max_width));
    if (d.max_height != 0) pl_node_set_len(n, kPlProp_MaxHeight, pl_px(d.max_height));
    if (d.bg != 0) pl_node_set_color(n, kPlProp_Background, d.bg);
    if (d.radius != 0) pl_node_set_f(n, kPlProp_Radius, d.radius);
    if (d.clip) pl_node_set_bool(n, kPlProp_Clip, true);
    if (d.padding != 0) pl_node_set_edge(n, kPlProp_Padding, pl_all(pl_px(d.padding)));
    if (d.border_width != 0 && d.border_color != 0) pl_node_set_color(n, kPlProp_BorderColor, d.border_color);
    if (d.border_width != 0) pl_node_set_f(n, kPlProp_BorderWidth, d.border_width);
    if (d.opacity != 0) pl_node_set_f(n, kPlProp_Opacity, d.opacity);
    if (d.grow != 0) pl_node_set_f(n, kPlProp_Grow, d.grow);
    if (d.shrink != 0) pl_node_set_f(n, kPlProp_Shrink, d.shrink);
    if (d.on_tap) pl_on(n, kPlEv_Tap, d.on_tap);
    if (d.child) pl_add_child(n, d.child);
    return n;
}

PlNode pl_row(PlCtx ctx, PlRowDesc d) {
    PlNode n = pl_make(ctx, "pl.Row");
    if (d.gap != 0) pl_node_set_f(n, kPlProp_Gap, d.gap);
    if (d.justify != 0) pl_node_set_enum(n, kPlProp_Justify, d.justify);
    if (d.align != 0) pl_node_set_enum(n, kPlProp_Align, d.align);
    pl_ui_gen_add_children(n, d.children);
    return n;
}

PlNode pl_column(PlCtx ctx, PlColumnDesc d) {
    PlNode n = pl_make(ctx, "pl.Column");
    if (d.gap != 0) pl_node_set_f(n, kPlProp_Gap, d.gap);
    if (d.justify != 0) pl_node_set_enum(n, kPlProp_Justify, d.justify);
    if (d.align != 0) pl_node_set_enum(n, kPlProp_Align, d.align);
    pl_ui_gen_add_children(n, d.children);
    return n;
}

PlNode pl_stack(PlCtx ctx, PlStackDesc d) {
    PlNode n = pl_make(ctx, "pl.Stack");
    if (d.width != 0) pl_node_set_len(n, kPlProp_Width, pl_px(d.width));
    if (d.height != 0) pl_node_set_len(n, kPlProp_Height, pl_px(d.height));
    if (d.justify != 0) pl_node_set_enum(n, kPlProp_Justify, d.justify);
    if (d.align != 0) pl_node_set_enum(n, kPlProp_Align, d.align);
    pl_ui_gen_add_children(n, d.children);
    return n;
}

PlNode pl_portal(PlCtx ctx, PlPortalDesc d) {
    PlNode n = pl_make(ctx, "pl.Portal");
    pl_node_set_bool(n, kPlProp_Portal, true);
    if (d.x != 0) pl_node_set_f(n, kPlProp_OverlayX, d.x);
    if (d.y != 0) pl_node_set_f(n, kPlProp_OverlayY, d.y);
    if (d.z != 0) pl_node_set_i(n, kPlProp_ZIndex, d.z);
    if (d.anchor) pl_node_set_bool(n, kPlProp_OverlayAnchor, true);
    if (d.flip) pl_node_set_bool(n, kPlProp_OverlayFlip, true);
    if (d.child) pl_add_child(n, d.child);
    return n;
}

PlNode pl_text(PlCtx ctx, PlTextDesc d) {
    PlNode n = pl_make(ctx, "pl.Text");
    if (d.text) pl_node_set_str(n, kPlProp_Text, d.text);
    if (d.size != 0) pl_node_set_f(n, kPlProp_FontSize, d.size);
    if (d.color != 0) pl_node_set_color(n, kPlProp_Color, d.color);
    if (d.grow != 0) pl_node_set_f(n, kPlProp_Grow, d.grow);
    if (d.ellipsis) pl_node_set_bool(n, kPlPropText_Ellipsis, true);
    if (d.wrap) pl_node_set_bool(n, kPlPropText_Wrap, true);
    if (d.dir != 0) pl_node_set_enum(n, kPlPropText_Dir, d.dir);
    return n;
}

PlNode pl_image(PlCtx ctx, PlImageDesc d) {
    PlNode n = pl_make(ctx, "pl.Image");
    if (d.src) pl_node_set_ptr(n, kPlPropImage_Src, (void*)d.src);
    if (d.width != 0) pl_node_set_len(n, kPlProp_Width, pl_px(d.width));
    if (d.height != 0) pl_node_set_len(n, kPlProp_Height, pl_px(d.height));
    if (d.radius != 0) pl_node_set_f(n, kPlProp_Radius, d.radius);
    if (d.grow != 0) pl_node_set_f(n, kPlProp_Grow, d.grow);
    return n;
}

PlNode pl_button(PlCtx ctx, PlButtonDesc d) {
    PlNode n = pl_make(ctx, "pl.Button");
    if (d.label) pl_node_set_str(n, kPlProp_Text, d.label);
    if (d.bg != 0) pl_node_set_color(n, kPlProp_Background, d.bg);
    if (d.color != 0) pl_node_set_color(n, kPlProp_Color, d.color);
    if (d.radius != 0) pl_node_set_f(n, kPlProp_Radius, d.radius);
    if (d.width != 0) pl_node_set_len(n, kPlProp_Width, pl_px(d.width));
    if (d.height != 0) pl_node_set_len(n, kPlProp_Height, pl_px(d.height));
    if (d.font_size != 0) pl_node_set_f(n, kPlProp_FontSize, d.font_size);
    if (d.on_press) pl_node_set_ptr(n, kPlPropButton_OnPress, (void*)d.on_press);
    return n;
}

PlNode pl_spacer(PlCtx ctx) {
    PlNode n = pl_make(ctx, "pl.Spacer");
    pl_node_set_f(n, kPlProp_Grow, 1.0f);
    return n;
}

PlNode pl_divider(PlCtx ctx, PlDividerDesc d) {
    PlNode n = pl_make(ctx, "pl.Divider");
    if (d.color != 0) pl_node_set_color(n, kPlProp_Color, d.color);
    if (d.thickness != 0) pl_node_set_len(n, kPlProp_Height, pl_px(d.thickness));
    if (d.vertical) pl_node_set_bool(n, kPlPropDivider_Vertical, true);
    return n;
}

PlNode pl_scroll(PlCtx ctx, PlScrollDesc d) {
    PlNode n = pl_make(ctx, "pl.Scroll");
    pl_node_set_bool(n, kPlProp_Clip, true);
    if (d.width != 0) pl_node_set_len(n, kPlProp_Width, pl_px(d.width));
    if (d.height != 0) pl_node_set_len(n, kPlProp_Height, pl_px(d.height));
    pl_node_set_f(n, kPlPropScroll_Y, d.scroll);
    if (d.scroll_x != 0) pl_node_set_f(n, kPlPropScroll_X, d.scroll_x);
    if (d.scrollbar) pl_node_set_bool(n, kPlPropScroll_Bar, true);
    if (d.child) pl_add_child(n, d.child);
    return n;
}

PlNode pl_grid(PlCtx ctx, PlGridDesc d) {
    PlNode n = pl_make(ctx, "pl.Grid");
    if (d.cols != 0) pl_node_set_i(n, kPlPropGrid_Cols, d.cols);
    if (d.gap != 0) pl_node_set_f(n, kPlProp_Gap, d.gap);
    if (d.autofit != 0) pl_node_set_i(n, kPlPropGrid_Auto, d.autofit);
    if (d.min_w != 0) pl_node_set_f(n, kPlPropGrid_MinW, d.min_w);
    if (d.max_w != 0) pl_node_set_f(n, kPlPropGrid_MaxW, d.max_w);
    if (d.min_h != 0) pl_node_set_f(n, kPlPropGrid_MinH, d.min_h);
    if (d.max_h != 0) pl_node_set_f(n, kPlPropGrid_MaxH, d.max_h);
    pl_ui_gen_add_children(n, d.children);
    return n;
}

PlNode pl_input(PlCtx ctx, PlInputDesc d) {
    PlNode n = pl_make(ctx, "pl.Input");
    if (d.value) pl_node_set_str(n, kPlPropInput_Value, d.value);
    if (d.placeholder) pl_node_set_str(n, kPlPropInput_Placeholder, d.placeholder);
    if (d.on_change) pl_node_set_ptr(n, kPlPropInput_OnChange, (void*)d.on_change);
    if (d.on_submit) pl_node_set_ptr(n, kPlPropInput_OnSubmit, (void*)d.on_submit);
    if (d.disabled) pl_node_set_bool(n, kPlPropInput_Disabled, true);
    if (d.password) pl_node_set_bool(n, kPlPropInput_Password, true);
    if (d.width != 0) pl_node_set_len(n, kPlProp_Width, pl_px(d.width));
    if (d.height != 0) pl_node_set_len(n, kPlProp_Height, pl_px(d.height));
    return n;
}

PlNode pl_textarea(PlCtx ctx, PlTextAreaDesc d) {
    PlNode n = pl_make(ctx, "pl.TextArea");
    if (d.value) pl_node_set_str(n, kPlPropTextArea_Value, d.value);
    if (d.placeholder) pl_node_set_str(n, kPlPropTextArea_Placeholder, d.placeholder);
    if (d.on_change) pl_node_set_ptr(n, kPlPropTextArea_OnChange, (void*)d.on_change);
    if (d.rows != 0) pl_node_set_enum(n, kPlPropTextArea_Rows, d.rows);
    if (d.dir != 0) pl_node_set_enum(n, kPlPropTextArea_Dir, d.dir);
    if (d.disabled) pl_node_set_bool(n, kPlPropTextArea_Disabled, true);
    if (d.width != 0) pl_node_set_len(n, kPlProp_Width, pl_px(d.width));
    if (d.height != 0) pl_node_set_len(n, kPlProp_Height, pl_px(d.height));
    return n;
}

PlNode pl_checkbox(PlCtx ctx, PlCheckboxDesc d) {
    PlNode n = pl_make(ctx, "pl.Checkbox");
    if (d.checked) pl_node_set_bool(n, kPlPropCheckbox_Checked, true);
    if (d.on_change) pl_node_set_ptr(n, kPlPropCheckbox_OnChange, (void*)d.on_change);
    if (d.disabled) pl_node_set_bool(n, kPlPropCheckbox_Disabled, true);
    return n;
}

PlNode pl_switch(PlCtx ctx, PlSwitchDesc d) {
    PlNode n = pl_make(ctx, "pl.Switch");
    if (d.on) pl_node_set_bool(n, kPlPropSwitch_On, true);
    if (d.on_change) pl_node_set_ptr(n, kPlPropSwitch_OnChange, (void*)d.on_change);
    if (d.disabled) pl_node_set_bool(n, kPlPropSwitch_Disabled, true);
    return n;
}

PlNode pl_slider(PlCtx ctx, PlSliderDesc d) {
    PlNode n = pl_make(ctx, "pl.Slider");
    if (d.value != 0) pl_node_set_f(n, kPlPropSlider_Value, d.value);
    if (d.on_change) pl_node_set_ptr(n, kPlPropSlider_OnChange, (void*)d.on_change);
    if (d.disabled) pl_node_set_bool(n, kPlPropSlider_Disabled, true);
    return n;
}

PlNode pl_select(PlCtx ctx, PlSelectDesc d) {
    PlNode n = pl_make(ctx, "pl.Select");
    if (d.value != 0) pl_node_set_i(n, kPlPropSelect_Value, d.value);
    if (d.placeholder) pl_node_set_str(n, kPlPropSelect_Placeholder, d.placeholder);
    if (d.on_change) pl_node_set_ptr(n, kPlPropSelect_OnChange, (void*)d.on_change);
    if (d.options) pl_node_set_ptr(n, kPlPropSelect_Options, (void*)d.options);
    if (d.option_count != 0) pl_node_set_i(n, kPlPropSelect_OptionCount, d.option_count);
    if (d.disabled) pl_node_set_bool(n, kPlPropSelect_Disabled, true);
    return n;
}

PlNode pl_progress(PlCtx ctx, PlProgressDesc d) {
    PlNode n = pl_make(ctx, "pl.Progress");
    if (d.value != 0) pl_node_set_f(n, kPlPropProgress_Value, d.value);
    if (d.thickness != 0) pl_node_set_f(n, kPlPropProgress_Thickness, d.thickness);
    if (d.width != 0) pl_node_set_len(n, kPlProp_Width, pl_px(d.width));
    return n;
}

PlNode pl_modal(PlCtx ctx, PlModalDesc d) {
    PlNode n = pl_make(ctx, "pl.Modal");
    if (d.open) pl_node_set_bool(n, kPlPropModal_Open, true);
    if (d.on_close) pl_node_set_ptr(n, kPlPropModal_OnClose, (void*)d.on_close);
    if (d.child) pl_node_set_ptr(n, kPlPropModal_Child, (void*)d.child);
    return n;
}

PlNode pl_tooltip(PlCtx ctx, PlTooltipDesc d) {
    PlNode n = pl_make(ctx, "pl.Tooltip");
    if (d.content) pl_node_set_str(n, kPlPropTooltip_Content, d.content);
    if (d.delay != 0) pl_node_set_f(n, kPlPropTooltip_Delay, d.delay);
    if (d.child) pl_node_set_ptr(n, kPlPropTooltip_ChildNode, (void*)d.child);
    return n;
}

PlNode pl_radio(PlCtx ctx, PlRadioDesc d) {
    PlNode n = pl_make(ctx, "pl.Radio");
    if (d.checked) pl_node_set_bool(n, kPlPropRadio_Checked, true);
    if (d.on_change) pl_node_set_ptr(n, kPlPropRadio_OnChange, (void*)d.on_change);
    if (d.disabled) pl_node_set_bool(n, kPlPropRadio_Disabled, true);
    return n;
}

PlNode pl_badge(PlCtx ctx, PlBadgeDesc d) {
    PlNode n = pl_make(ctx, "pl.Badge");
    if (d.count != 0) pl_node_set_i(n, kPlPropBadge_Count, d.count);
    if (d.content) pl_node_set_str(n, kPlPropBadge_Content, d.content);
    if (d.color != 0) pl_node_set_color(n, kPlPropBadge_Color, d.color);
    if (d.child) pl_node_set_ptr(n, kPlPropBadge_ChildNode, (void*)d.child);
    return n;
}

PlNode pl_chip(PlCtx ctx, PlChipDesc d) {
    PlNode n = pl_make(ctx, "pl.Chip");
    if (d.label) pl_node_set_str(n, kPlPropChip_Label, d.label);
    if (d.selected) pl_node_set_bool(n, kPlPropChip_Selected, true);
    if (d.on_tap) pl_node_set_ptr(n, kPlPropChip_OnTap, (void*)d.on_tap);
    if (d.on_remove) pl_node_set_ptr(n, kPlPropChip_OnRemove, (void*)d.on_remove);
    if (d.disabled) pl_node_set_bool(n, kPlPropChip_Disabled, true);
    return n;
}

PlNode pl_accordion(PlCtx ctx, PlAccordionDesc d) {
    PlNode n = pl_make(ctx, "pl.Accordion");
    if (d.title) pl_node_set_str(n, kPlPropAccordion_Title, d.title);
    if (d.open) pl_node_set_bool(n, kPlPropAccordion_Open, true);
    if (d.on_toggle) pl_node_set_ptr(n, kPlPropAccordion_OnToggle, (void*)d.on_toggle);
    if (d.child) pl_node_set_ptr(n, kPlPropAccordion_ChildNode, (void*)d.child);
    return n;
}

PlNode pl_tabs(PlCtx ctx, PlTabsDesc d) {
    PlNode n = pl_make(ctx, "pl.Tabs");
    if (d.active_index != 0) pl_node_set_i(n, kPlPropTabs_ActiveIndex, d.active_index);
    if (d.on_change) pl_node_set_ptr(n, kPlPropTabs_OnChange, (void*)d.on_change);
    if (d.labels) pl_node_set_ptr(n, kPlPropTabs_Labels, (void*)d.labels);
    if (d.count != 0) pl_node_set_i(n, kPlPropTabs_Count, d.count);
    return n;
}

PlNode pl_avatar(PlCtx ctx, PlAvatarDesc d) {
    PlNode n = pl_make(ctx, "pl.Avatar");
    if (d.initials) pl_node_set_str(n, kPlPropAvatar_Initials, d.initials);
    if (d.color != 0) pl_node_set_color(n, kPlPropAvatar_Color, d.color);
    if (d.size != 0) pl_node_set_f(n, kPlPropAvatar_Size, d.size);
    if (d.src) pl_node_set_ptr(n, kPlPropAvatar_Src, (void*)d.src);
    return n;
}

PlNode pl_list(PlCtx ctx, PlListDesc d) {
    PlNode n = pl_make(ctx, "pl.List");
    if (d.count != 0) pl_node_set_i(n, kPlPropList_Count, d.count);
    if (d.item_height != 0) pl_node_set_f(n, kPlPropList_ItemHeight, d.item_height);
    if (d.builder) pl_node_set_ptr(n, kPlPropList_Builder, (void*)d.builder);
    if (d.scroll_y != 0) pl_node_set_f(n, kPlPropList_ScrollY, d.scroll_y);
    if (d.on_scroll) pl_node_set_ptr(n, kPlPropList_OnScroll, (void*)d.on_scroll);
    if (d.height != 0) pl_node_set_f(n, kPlPropList_Height, d.height);
    if (d.width != 0) pl_node_set_f(n, kPlPropList_Width, d.width);
    return n;
}

PlNode pl_notification(PlCtx ctx, PlNotificationDesc d) {
    PlNode n = pl_make(ctx, "pl.Notification");
    if (d.message) pl_node_set_str(n, kPlPropNotification_Message, d.message);
    if (d.duration != 0) pl_node_set_f(n, kPlPropNotification_Duration, d.duration);
    if (d.variant != 0) pl_node_set_i(n, kPlPropNotification_Variant, d.variant);
    if (d.on_close) pl_node_set_ptr(n, kPlPropNotification_OnClose, (void*)d.on_close);
    if (d.visible) pl_node_set_bool(n, kPlPropNotification_Visible, true);
    return n;
}

PlNode pl_richtext(PlCtx ctx, PlRichTextDesc d) {
    PlNode n = pl_make(ctx, "pl.RichText");
    if (d.spans) pl_node_set_ptr(n, kPlPropRichText_Spans, (void*)d.spans);
    if (d.span_count != 0) pl_node_set_i(n, kPlPropRichText_SpanCount, d.span_count);
    if (d.wrap) pl_node_set_bool(n, kPlPropRichText_Wrap, true);
    return n;
}

PlNode pl_menu(PlCtx ctx, PlMenuDesc d) {
    PlNode n = pl_make(ctx, "pl.Menu");
    if (d.open) pl_node_set_bool(n, kPlPropMenu_Open, true);
    if (d.items) pl_node_set_ptr(n, kPlPropMenu_Items, (void*)d.items);
    if (d.item_count != 0) pl_node_set_i(n, kPlPropMenu_ItemCount, d.item_count);
    if (d.on_select) pl_node_set_ptr(n, kPlPropMenu_OnSelect, (void*)d.on_select);
    if (d.x != 0) pl_node_set_f(n, kPlPropMenu_X, d.x);
    if (d.y != 0) pl_node_set_f(n, kPlPropMenu_Y, d.y);
    return n;
}

PlNode pl_pagination(PlCtx ctx, PlPaginationDesc d) {
    PlNode n = pl_make(ctx, "pl.Pagination");
    if (d.page != 0) pl_node_set_i(n, kPlPropPagination_Page, d.page);
    if (d.page_count != 0) pl_node_set_i(n, kPlPropPagination_PageCount, d.page_count);
    if (d.on_change) pl_node_set_ptr(n, kPlPropPagination_OnChange, (void*)d.on_change);
    return n;
}

PlNode pl_colorpicker(PlCtx ctx, PlColorPickerDesc d) {
    PlNode n = pl_make(ctx, "pl.ColorPicker");
    if (d.value != 0) pl_node_set_color(n, kPlPropColorPicker_Value, d.value);
    if (d.on_change) pl_node_set_ptr(n, kPlPropColorPicker_OnChange, (void*)d.on_change);
    return n;
}

PlNode pl_datepicker(PlCtx ctx, PlDatePickerDesc d) {
    PlNode n = pl_make(ctx, "pl.DatePicker");
    if (d.year != 0) pl_node_set_i(n, kPlPropDatePicker_Year, d.year);
    if (d.month != 0) pl_node_set_i(n, kPlPropDatePicker_Month, d.month);
    if (d.day != 0) pl_node_set_i(n, kPlPropDatePicker_Day, d.day);
    if (d.on_change) pl_node_set_ptr(n, kPlPropDatePicker_OnChange, (void*)d.on_change);
    return n;
}

PlNode pl_stepper(PlCtx ctx, PlStepperDesc d) {
    PlNode n = pl_make(ctx, "pl.Stepper");
    if (d.value != 0) pl_node_set_i(n, kPlPropStepper_Value, d.value);
    if (d.min != 0) pl_node_set_i(n, kPlPropStepper_Min, d.min);
    if (d.max != 0) pl_node_set_i(n, kPlPropStepper_Max, d.max);
    if (d.step != 0) pl_node_set_i(n, kPlPropStepper_Step, d.step);
    if (d.on_change) pl_node_set_ptr(n, kPlPropStepper_OnChange, (void*)d.on_change);
    if (d.disabled) pl_node_set_bool(n, kPlPropStepper_Disabled, true);
    return n;
}

PlNode pl_rating(PlCtx ctx, PlRatingDesc d) {
    PlNode n = pl_make(ctx, "pl.Rating");
    if (d.value != 0) pl_node_set_i(n, kPlPropRating_Value, d.value);
    if (d.max != 0) pl_node_set_i(n, kPlPropRating_Max, d.max);
    if (d.on_change) pl_node_set_ptr(n, kPlPropRating_OnChange, (void*)d.on_change);
    if (d.read_only) pl_node_set_bool(n, kPlPropRating_ReadOnly, true);
    return n;
}

PlNode pl_timeline(PlCtx ctx, PlTimelineDesc d) {
    PlNode n = pl_make(ctx, "pl.Timeline");
    if (d.items) pl_node_set_ptr(n, kPlPropTimeline_Items, (void*)d.items);
    if (d.item_count != 0) pl_node_set_i(n, kPlPropTimeline_ItemCount, d.item_count);
    return n;
}

PlNode pl_table(PlCtx ctx, PlTableDesc d) {
    PlNode n = pl_make(ctx, "pl.Table");
    if (d.columns) pl_node_set_ptr(n, kPlPropTable_Columns, (void*)d.columns);
    if (d.column_count != 0) pl_node_set_i(n, kPlPropTable_ColumnCount, d.column_count);
    if (d.rows) pl_node_set_ptr(n, kPlPropTable_Rows, (void*)d.rows);
    if (d.row_count != 0) pl_node_set_i(n, kPlPropTable_RowCount, d.row_count);
    if (d.on_row_select) pl_node_set_ptr(n, kPlPropTable_OnRowSelect, (void*)d.on_row_select);
    if (d.selected_row != 0) pl_node_set_i(n, kPlPropTable_SelectedRow, d.selected_row);
    return n;
}

PlNode pl_splitpane(PlCtx ctx, PlSplitPaneDesc d) {
    PlNode n = pl_make(ctx, "pl.SplitPane");
    if (d.split != 0) pl_node_set_f(n, kPlPropSplitPane_Split, d.split);
    if (d.vertical) pl_node_set_bool(n, kPlPropSplitPane_Vertical, true);
    if (d.on_change) pl_node_set_ptr(n, kPlPropSplitPane_OnChange, (void*)d.on_change);
    if (d.first) pl_node_set_ptr(n, kPlPropSplitPane_First, (void*)d.first);
    if (d.second) pl_node_set_ptr(n, kPlPropSplitPane_Second, (void*)d.second);
    if (d.width != 0) pl_node_set_f(n, kPlPropSplitPane_Width, d.width);
    if (d.height != 0) pl_node_set_f(n, kPlPropSplitPane_Height, d.height);
    return n;
}

PlNode pl_carousel(PlCtx ctx, PlCarouselDesc d) {
    PlNode n = pl_make(ctx, "pl.Carousel");
    if (d.index != 0) pl_node_set_i(n, kPlPropCarousel_Index, d.index);
    if (d.count != 0) pl_node_set_i(n, kPlPropCarousel_Count, d.count);
    if (d.builder) pl_node_set_ptr(n, kPlPropCarousel_Builder, (void*)d.builder);
    if (d.on_change) pl_node_set_ptr(n, kPlPropCarousel_OnChange, (void*)d.on_change);
    if (d.width != 0) pl_node_set_f(n, kPlPropCarousel_Width, d.width);
    if (d.height != 0) pl_node_set_f(n, kPlPropCarousel_Height, d.height);
    return n;
}

PlNode pl_searchbar(PlCtx ctx, PlSearchBarDesc d) {
    PlNode n = pl_make(ctx, "pl.SearchBar");
    if (d.value) pl_node_set_str(n, kPlPropSearchBar_Value, d.value);
    if (d.placeholder) pl_node_set_str(n, kPlPropSearchBar_Placeholder, d.placeholder);
    if (d.on_change) pl_node_set_ptr(n, kPlPropSearchBar_OnChange, (void*)d.on_change);
    if (d.on_submit) pl_node_set_ptr(n, kPlPropSearchBar_OnSubmit, (void*)d.on_submit);
    if (d.on_clear) pl_node_set_ptr(n, kPlPropSearchBar_OnClear, (void*)d.on_clear);
    return n;
}

PlNode pl_breadcrumb(PlCtx ctx, PlBreadcrumbDesc d) {
    PlNode n = pl_make(ctx, "pl.Breadcrumb");
    if (d.items) pl_node_set_ptr(n, kPlPropBreadcrumb_Items, (void*)d.items);
    if (d.item_count != 0) pl_node_set_i(n, kPlPropBreadcrumb_ItemCount, d.item_count);
    if (d.on_click) pl_node_set_ptr(n, kPlPropBreadcrumb_OnClick, (void*)d.on_click);
    return n;
}
