/* ============================================================================
 * GENERATED by tools/gen_schema.py from schema/plume.schema.json —— 请勿手改。
 * 改动改 schema 后重跑生成器；CTest `schema_gen_drift` 会校验产物与 schema 一致。
 * ==========================================================================*/
#ifndef PLUME_SCHEMA_GEN_H
#define PLUME_SCHEMA_GEN_H
#include <plume/plume_kernel.h>
/* 模块属性 id 的【唯一定义】（= kPlProp_ModuleBase + 序号）。各控件直接用这些名字；
 * schema 是唯一真相源——新属性只在 schema 末尾追加（id 永不变）；勿在控件头手写 #define。*/
#define kPlPropImage_Src           (kPlProp_ModuleBase + 1)   /* ptr: CevgImage*（图像源，宿主持有生命周期） */
#define kPlPropButton_OnPress      (kPlProp_ModuleBase + 2)   /* ptr: PlHandler（按下动作） */
#define kPlPropText_Ellipsis       (kPlProp_ModuleBase + 3)   /* bool: 放不下时尾部省略号截断 */
#define kPlPropText_Wrap           (kPlProp_ModuleBase + 4)   /* bool: 超宽时按词换行（多行） */
#define kPlPropScroll_Y            (kPlProp_ModuleBase + 5)   /* float: 竖直滚动偏移（内容上移量） */
#define kPlPropDivider_Vertical    (kPlProp_ModuleBase + 6)   /* bool: 竖向分隔线（填高×厚），默认横向 */
#define kPlPropScroll_Bar          (kPlProp_ModuleBase + 7)   /* bool: 显示滚动条指示器（双轴：内容溢出哪轴显哪轴） */
#define kPlPropGrid_Cols           (kPlProp_ModuleBase + 8)   /* int: 列数（默认 2） */
#define kPlPropGrid_Auto           (kPlProp_ModuleBase + 9)   /* int: 列宽按内容自适应（默认 0=等宽） */
#define kPlPropGrid_MinW           (kPlProp_ModuleBase + 10)   /* float: 自适应时每列最小宽（默认 0） */
#define kPlPropGrid_MaxW           (kPlProp_ModuleBase + 11)   /* float: 自适应时每列最大宽（默认 0=不封顶） */
#define kPlPropGrid_MinH           (kPlProp_ModuleBase + 12)   /* float: 每行最小高（默认 0=不保底） */
#define kPlPropGrid_MaxH           (kPlProp_ModuleBase + 13)   /* float: 每行最大高（默认 0=不封顶） */
#define kPlPropScroll_X            (kPlProp_ModuleBase + 14)   /* float: 水平滚动偏移（内容左移量）——尾部追加，2D 滚动用 */
#define kPlPropInput_Value         (kPlProp_ModuleBase + 15)   /* str: 输入框当前值（受控） */
#define kPlPropInput_Placeholder   (kPlProp_ModuleBase + 16)   /* str: 无值时的占位提示文字 */
#define kPlPropInput_OnChange      (kPlProp_ModuleBase + 17)   /* ptr: PlHandler：值变化时触发（新值通过 pl_event_text 读取） */
#define kPlPropInput_Disabled      (kPlProp_ModuleBase + 18)   /* bool: 禁用态：不可聚焦/不接受输入 */
#define kPlPropInput_Password      (kPlProp_ModuleBase + 19)   /* bool: 密码模式：显示 • 替代字符 */
#define kPlPropInput_OnSubmit      (kPlProp_ModuleBase + 20)   /* ptr: PlHandler：按 Enter 时触发 */
#define kPlPropCheckbox_Checked    (kPlProp_ModuleBase + 21)   /* bool: 勾选状态 */
#define kPlPropCheckbox_OnChange   (kPlProp_ModuleBase + 22)   /* ptr: PlHandler：点击切换时触发 */
#define kPlPropCheckbox_Disabled   (kPlProp_ModuleBase + 23)   /* bool: 禁用态 */
#define kPlPropSwitch_On           (kPlProp_ModuleBase + 24)   /* bool: 开关状态 */
#define kPlPropSwitch_OnChange     (kPlProp_ModuleBase + 25)   /* ptr: PlHandler：切换时触发 */
#define kPlPropSwitch_Disabled     (kPlProp_ModuleBase + 26)   /* bool: 禁用态 */
#define kPlPropSlider_Value        (kPlProp_ModuleBase + 27)   /* float: 当前值（0.0–1.0） */
#define kPlPropSlider_OnChange     (kPlProp_ModuleBase + 28)   /* ptr: PlHandler：拖动时触发 */
#define kPlPropSlider_Disabled     (kPlProp_ModuleBase + 29)   /* bool: 禁用态 */
#define kPlPropSelect_Value        (kPlProp_ModuleBase + 30)   /* int: 当前选中项索引（-1=未选） */
#define kPlPropSelect_OnChange     (kPlProp_ModuleBase + 31)   /* ptr: PlHandler：选中项变化时触发 */
#define kPlPropSelect_Placeholder  (kPlProp_ModuleBase + 32)   /* str: 未选中时的提示文字 */
#define kPlPropProgress_Value      (kPlProp_ModuleBase + 33)   /* float: 进度值 0.0–1.0；负值=不确定（旋转 spinner） */
#define kPlPropProgress_Thickness  (kPlProp_ModuleBase + 34)   /* float: 轨道粗细（默认 6） */
#define kPlPropModal_Open          (kPlProp_ModuleBase + 35)   /* bool: 是否展示模态层 */
#define kPlPropModal_OnClose       (kPlProp_ModuleBase + 36)   /* ptr: PlHandler：点击遮罩/Esc 时触发 */
#define kPlPropModal_Child         (kPlProp_ModuleBase + 37)   /* PlNode: 模态内容（自动居中） */
#define kPlPropTooltip_Content     (kPlProp_ModuleBase + 38)   /* str: 提示文字 */
#define kPlPropTooltip_Child       (kPlProp_ModuleBase + 39)   /* PlNode: 触发元素（hover 后显示 tooltip） */
#define kPlPropTooltip_Delay       (kPlProp_ModuleBase + 40)   /* float: 延迟显示时间秒（默认 0.3） */
#define kPlPropRadio_Checked       (kPlProp_ModuleBase + 41)   /* bool: 选中状态 */
#define kPlPropRadio_OnChange      (kPlProp_ModuleBase + 42)   /* ptr: PlHandler：点击时触发（pl_event_text='1'） */
#define kPlPropRadio_Disabled      (kPlProp_ModuleBase + 43)   /* bool: 禁用态 */
#define kPlPropBadge_Count         (kPlProp_ModuleBase + 44)   /* int: 徽章数字（0=隐藏，>99 显示 99+） */
#define kPlPropBadge_Content       (kPlProp_ModuleBase + 45)   /* str: 徽章文字（优先于 Count）；NULL=用 Count */
#define kPlPropBadge_Color         (kPlProp_ModuleBase + 46)   /* PlColor: 0=默认红色 */
#define kPlPropChip_Label          (kPlProp_ModuleBase + 47)   /* str: 标签文字 */
#define kPlPropChip_Selected       (kPlProp_ModuleBase + 48)   /* bool: 选中态（高亮背景） */
#define kPlPropChip_OnTap          (kPlProp_ModuleBase + 49)   /* ptr: PlHandler：点击回调 */
#define kPlPropChip_OnRemove       (kPlProp_ModuleBase + 50)   /* ptr: PlHandler：删除按钮回调（NULL=不显示 ×） */
#define kPlPropChip_Disabled       (kPlProp_ModuleBase + 51)   /* bool: 禁用态 */
#define kPlPropAccordion_Title     (kPlProp_ModuleBase + 52)   /* str: 标题文字 */
#define kPlPropAccordion_Open      (kPlProp_ModuleBase + 53)   /* bool: 展开状态 */
#define kPlPropAccordion_OnToggle  (kPlProp_ModuleBase + 54)   /* ptr: PlHandler：点击标题时触发 */
#define kPlPropAccordion_Child     (kPlProp_ModuleBase + 55)   /* PlNode: 折叠内容 */
#define kPlPropSelect_Options      (kPlProp_ModuleBase + 56)   /* ptr: const char** 选项数组（以 NULL 结尾） */
#define kPlPropSelect_OptionCount  (kPlProp_ModuleBase + 57)   /* int: 选项数量（与 Options 配合使用） */
#define kPlPropSelect_Disabled     (kPlProp_ModuleBase + 58)   /* bool: 禁用态 */
#define kPlPropBadge_ChildNode     (kPlProp_ModuleBase + 59)   /* ptr: 内部：子节点 PlNode ptr */
#define kPlPropAccordion_ChildNode (kPlProp_ModuleBase + 60)   /* ptr: 内部：子节点 PlNode ptr */
#define kPlPropTooltip_ChildNode   (kPlProp_ModuleBase + 61)   /* ptr: 内部：触发节点 PlNode ptr */
#define kPlPropTabs_ActiveIndex    (kPlProp_ModuleBase + 62)   /* int: 当前激活 Tab 索引（0 起） */
#define kPlPropTabs_OnChange       (kPlProp_ModuleBase + 63)   /* ptr: PlHandler：切换时触发；pl_event_text='N' */
#define kPlPropTabs_Labels         (kPlProp_ModuleBase + 64)   /* ptr: const char** 标签数组（NULL 结尾 or 配合 Count） */
#define kPlPropTabs_Count          (kPlProp_ModuleBase + 65)   /* int: 标签数量 */
#define kPlPropAvatar_Initials     (kPlProp_ModuleBase + 66)   /* str: 首字母缩写（1-2字符，图片不可用时显示） */
#define kPlPropAvatar_Color        (kPlProp_ModuleBase + 67)   /* PlColor: 背景色（0=按 initials hash 自动选） */
#define kPlPropAvatar_Size         (kPlProp_ModuleBase + 68)   /* float: 直径 px（默认 40） */
#define kPlPropAvatar_Src          (kPlProp_ModuleBase + 69)   /* ptr: CevgImage* 图片源（NULL=仅显示首字母） */
#define kPlPropList_Count          (kPlProp_ModuleBase + 70)   /* int: 列表项总数 */
#define kPlPropList_ItemHeight     (kPlProp_ModuleBase + 71)   /* float: 每项等高 px（默认 48） */
#define kPlPropList_Builder        (kPlProp_ModuleBase + 72)   /* ptr: PlListBuilder：(ctx,idx)→PlNode 构建每项 */
#define kPlPropList_ScrollY        (kPlProp_ModuleBase + 73)   /* float: 当前滚动偏移（受控） */
#define kPlPropList_OnScroll       (kPlProp_ModuleBase + 74)   /* ptr: PlHandler：滚动时触发 */
#define kPlPropList_Height         (kPlProp_ModuleBase + 75)   /* float: 视口高度 px */
#define kPlPropList_Width          (kPlProp_ModuleBase + 76)   /* float: 视口宽度 px */
#define kPlPropNotification_Message (kPlProp_ModuleBase + 77)   /* str: 通知文字 */
#define kPlPropNotification_Duration (kPlProp_ModuleBase + 78)   /* float: 显示时长秒（默认 3.0，0=不自动消失） */
#define kPlPropNotification_Variant (kPlProp_ModuleBase + 79)   /* int: kPlNotify_Info=0/Success=1/Warning=2/Error=3 */
#define kPlPropNotification_OnClose (kPlProp_ModuleBase + 80)   /* ptr: PlHandler：消失时触发 */
#define kPlPropNotification_Visible (kPlProp_ModuleBase + 81)   /* bool: 是否显示（受控） */
#define kPlPropRichText_Spans      (kPlProp_ModuleBase + 82)   /* ptr: PlSpan* 数组（指向 PlSpan[]） */
#define kPlPropRichText_SpanCount  (kPlProp_ModuleBase + 83)   /* int: Span 数量 */
#define kPlPropRichText_Wrap       (kPlProp_ModuleBase + 84)   /* bool: 换行 */
#define kPlPropScroll_BarTrack     (kPlProp_ModuleBase + 85)   /* PlColor: 滚动条轨道色（0=默认灰） */
#define kPlPropScroll_BarThumb     (kPlProp_ModuleBase + 86)   /* PlColor: 滚动条滑块色（0=默认蓝灰） */
#define kPlPropMenu_Open           (kPlProp_ModuleBase + 87)   /* bool: 是否展开 */
#define kPlPropMenu_Items          (kPlProp_ModuleBase + 88)   /* ptr: PlMenuItem* 数组 */
#define kPlPropMenu_ItemCount      (kPlProp_ModuleBase + 89)   /* int: 菜单项数 */
#define kPlPropMenu_OnSelect       (kPlProp_ModuleBase + 90)   /* ptr: PlHandler：选中项时触发；pl_event_text=item id */
#define kPlPropMenu_X              (kPlProp_ModuleBase + 91)   /* float: 菜单弹出 x 坐标 */
#define kPlPropMenu_Y              (kPlProp_ModuleBase + 92)   /* float: 菜单弹出 y 坐标 */
#define kPlPropPagination_Page     (kPlProp_ModuleBase + 93)   /* int: 当前页（1 起） */
#define kPlPropPagination_PageCount (kPlProp_ModuleBase + 94)   /* int: 总页数 */
#define kPlPropPagination_OnChange (kPlProp_ModuleBase + 95)   /* ptr: PlHandler；pl_event_text='N' */
#define kPlPropColorPicker_Value   (kPlProp_ModuleBase + 96)   /* PlColor: 当前颜色 0xRRGGBBAA */
#define kPlPropColorPicker_OnChange (kPlProp_ModuleBase + 97)   /* ptr: PlHandler；pl_event_text='RRGGBBAA' */
#define kPlPropDatePicker_Year     (kPlProp_ModuleBase + 98)   /* int: 年 */
#define kPlPropDatePicker_Month    (kPlProp_ModuleBase + 99)   /* int: 月（1-12） */
#define kPlPropDatePicker_Day      (kPlProp_ModuleBase + 100)   /* int: 日（1-31） */
#define kPlPropDatePicker_OnChange (kPlProp_ModuleBase + 101)   /* ptr: PlHandler；pl_event_text='YYYY-MM-DD' */
#define kPlPropStepper_Value       (kPlProp_ModuleBase + 102)   /* int: 当前值 */
#define kPlPropStepper_Min         (kPlProp_ModuleBase + 103)   /* int: 最小值（默认 0） */
#define kPlPropStepper_Max         (kPlProp_ModuleBase + 104)   /* int: 最大值（默认 99） */
#define kPlPropStepper_Step        (kPlProp_ModuleBase + 105)   /* int: 步进量（默认 1） */
#define kPlPropStepper_OnChange    (kPlProp_ModuleBase + 106)   /* ptr: PlHandler；pl_event_text='N' */
#define kPlPropStepper_Disabled    (kPlProp_ModuleBase + 107)   /* bool: 禁用 */
#define kPlPropRating_Value        (kPlProp_ModuleBase + 108)   /* int: 当前评分（0-5） */
#define kPlPropRating_Max          (kPlProp_ModuleBase + 109)   /* int: 最大星数（默认 5） */
#define kPlPropRating_OnChange     (kPlProp_ModuleBase + 110)   /* ptr: PlHandler；pl_event_text='N' */
#define kPlPropRating_ReadOnly     (kPlProp_ModuleBase + 111)   /* bool: 只读 */
#define kPlPropTimeline_Items      (kPlProp_ModuleBase + 112)   /* ptr: PlTimelineItem* 数组 */
#define kPlPropTimeline_ItemCount  (kPlProp_ModuleBase + 113)   /* int: 数量 */
#define kPlPropText_LineHeight     (kPlProp_ModuleBase + 114)   /* float: 行高比例（默认 1.2） */
#define kPlPropText_LetterSpacing  (kPlProp_ModuleBase + 115)   /* float: 字间距 px（默认 0） */
#define kPlPropBox_RadiusTL        (kPlProp_ModuleBase + 116)   /* float: 左上圆角（0=跟 Radius） */
#define kPlPropBox_RadiusTR        (kPlProp_ModuleBase + 117)   /* float: 右上圆角 */
#define kPlPropBox_RadiusBR        (kPlProp_ModuleBase + 118)   /* float: 右下圆角 */
#define kPlPropBox_RadiusBL        (kPlProp_ModuleBase + 119)   /* float: 左下圆角 */
#define kPlPropTable_Columns       (kPlProp_ModuleBase + 120)   /* ptr: PlTableColumn* 列定义数组 */
#define kPlPropTable_ColumnCount   (kPlProp_ModuleBase + 121)   /* int: 列数 */
#define kPlPropTable_Rows          (kPlProp_ModuleBase + 122)   /* ptr: const char** 数据（rows×cols 行主序） */
#define kPlPropTable_RowCount      (kPlProp_ModuleBase + 123)   /* int: 行数（不含表头） */
#define kPlPropTable_OnRowSelect   (kPlProp_ModuleBase + 124)   /* ptr: PlHandler；pl_event_text='row_idx' */
#define kPlPropTable_SelectedRow   (kPlProp_ModuleBase + 125)   /* int: 选中行索引（-1=无） */
#define kPlPropSplitPane_Split     (kPlProp_ModuleBase + 126)   /* float: 分割比例 0.0-1.0（默认 0.5） */
#define kPlPropSplitPane_Vertical  (kPlProp_ModuleBase + 127)   /* bool: true=左右分割，false=上下分割 */
#define kPlPropSplitPane_OnChange  (kPlProp_ModuleBase + 128)   /* ptr: PlHandler；pl_event_text='0.000' */
#define kPlPropSplitPane_First     (kPlProp_ModuleBase + 129)   /* ptr: PlNode：第一个面板 */
#define kPlPropSplitPane_Second    (kPlProp_ModuleBase + 130)   /* ptr: PlNode：第二个面板 */
#define kPlPropSplitPane_Width     (kPlProp_ModuleBase + 131)   /* float: 总宽度 px（vertical=true 时） */
#define kPlPropSplitPane_Height    (kPlProp_ModuleBase + 132)   /* float: 总高度 px */
#define kPlPropCarousel_Index      (kPlProp_ModuleBase + 133)   /* int: 当前显示项索引（0 起） */
#define kPlPropCarousel_Count      (kPlProp_ModuleBase + 134)   /* int: 总项数 */
#define kPlPropCarousel_Builder    (kPlProp_ModuleBase + 135)   /* ptr: PlListBuilder：(ctx,idx)→PlNode */
#define kPlPropCarousel_OnChange   (kPlProp_ModuleBase + 136)   /* ptr: PlHandler；pl_event_text='N' */
#define kPlPropCarousel_Width      (kPlProp_ModuleBase + 137)   /* float: 每项宽 px（默认 300） */
#define kPlPropCarousel_Height     (kPlProp_ModuleBase + 138)   /* float: 高度 px（默认 200） */
#define kPlPropSearchBar_Value     (kPlProp_ModuleBase + 139)   /* str: 搜索框当前文字 */
#define kPlPropSearchBar_Placeholder (kPlProp_ModuleBase + 140)   /* str: 提示文字（默认 'Search...'） */
#define kPlPropSearchBar_OnChange  (kPlProp_ModuleBase + 141)   /* ptr: PlHandler；pl_event_text=new value */
#define kPlPropSearchBar_OnSubmit  (kPlProp_ModuleBase + 142)   /* ptr: PlHandler；回车确认 */
#define kPlPropSearchBar_OnClear   (kPlProp_ModuleBase + 143)   /* ptr: PlHandler；清除按钮 */
#define kPlPropBreadcrumb_Items    (kPlProp_ModuleBase + 144)   /* ptr: const char** 路径项数组（NULL 结尾） */
#define kPlPropBreadcrumb_ItemCount (kPlProp_ModuleBase + 145)   /* int: 路径项数 */
#define kPlPropBreadcrumb_OnClick  (kPlProp_ModuleBase + 146)   /* ptr: PlHandler；pl_event_text='idx' */
#define kPlPropImage_Fit           (kPlProp_ModuleBase + 147)   /* int: 0=fill 1=contain 2=cover */
#define kPlPropButton_IconLeft     (kPlProp_ModuleBase + 148)   /* PlNode: 左侧图标节点 */
#define kPlPropButton_IconRight    (kPlProp_ModuleBase + 149)   /* PlNode: 右侧图标节点 */
#define kPlPropButton_Loading      (kPlProp_ModuleBase + 150)   /* bool: 加载态（旋转 spinner） */
#define kPlPropText_Dir            (kPlProp_ModuleBase + 151)   /* int: 文本方向 kPlDir_Auto/LTR/RTL */
#define kPlPropTextArea_Value      (kPlProp_ModuleBase + 152)   /* str: 当前值（受控，可含换行） */
#define kPlPropTextArea_Placeholder (kPlProp_ModuleBase + 153)   /* str: 占位文字 */
#define kPlPropTextArea_OnChange   (kPlProp_ModuleBase + 154)   /* ptr: PlHandler 值变化回调 */
#define kPlPropTextArea_Rows       (kPlProp_ModuleBase + 155)   /* int: 可见行数 */
#define kPlPropTextArea_Dir        (kPlProp_ModuleBase + 156)   /* int: 文本方向 */
#define kPlPropTextArea_Disabled   (kPlProp_ModuleBase + 157)   /* bool: 禁用态 */
#define kPlPropTextArea_Cursor     (kPlProp_ModuleBase + 158)   /* int: 内部：光标字节偏移（传给视图） */
#define kPlPropTextArea_Anchor     (kPlProp_ModuleBase + 159)   /* int: 内部：选区锚点字节偏移（传给视图） */
#define kPlPropText_InkCenter      (kPlProp_ModuleBase + 160)   /* bool: 按墨迹盒垂直居中（补偿 CJK 字形上下偏移） */

#endif /* PLUME_SCHEMA_GEN_H */
