/* ============================================================================
 * GENERATED by tools/gen_schema.py from schema/plume.schema.json —— 请勿手改。
 * 改动改 schema 后重跑生成器；CTest `schema_gen_drift` 会校验产物与 schema 一致。
 * ==========================================================================*/
#include "pl_schema_table.h"
#include "plume_schema_gen.h"

static const PlSchemaProp k_props_Box[] = { { "RadiusTL", "float", kPlPropBox_RadiusTL }, { "RadiusTR", "float", kPlPropBox_RadiusTR }, { "RadiusBR", "float", kPlPropBox_RadiusBR }, { "RadiusBL", "float", kPlPropBox_RadiusBL } };
static const PlSchemaProp k_props_Text[] = { { "Ellipsis", "bool", kPlPropText_Ellipsis }, { "Wrap", "bool", kPlPropText_Wrap }, { "LineHeight", "float", kPlPropText_LineHeight }, { "LetterSpacing", "float", kPlPropText_LetterSpacing }, { "Dir", "int", kPlPropText_Dir }, { "InkCenter", "bool", kPlPropText_InkCenter } };
static const PlSchemaProp k_props_Image[] = { { "Src", "ptr", kPlPropImage_Src }, { "Fit", "int", kPlPropImage_Fit } };
static const PlSchemaProp k_props_Button[] = { { "OnPress", "ptr", kPlPropButton_OnPress }, { "IconLeft", "PlNode", kPlPropButton_IconLeft }, { "IconRight", "PlNode", kPlPropButton_IconRight }, { "Loading", "bool", kPlPropButton_Loading } };
static const PlSchemaProp k_props_Divider[] = { { "Vertical", "bool", kPlPropDivider_Vertical } };
static const PlSchemaProp k_props_Scroll[] = { { "Y", "float", kPlPropScroll_Y }, { "Bar", "bool", kPlPropScroll_Bar }, { "X", "float", kPlPropScroll_X }, { "BarTrack", "PlColor", kPlPropScroll_BarTrack }, { "BarThumb", "PlColor", kPlPropScroll_BarThumb } };
static const PlSchemaProp k_props_Grid[] = { { "Cols", "int", kPlPropGrid_Cols }, { "Auto", "int", kPlPropGrid_Auto }, { "MinW", "float", kPlPropGrid_MinW }, { "MaxW", "float", kPlPropGrid_MaxW }, { "MinH", "float", kPlPropGrid_MinH }, { "MaxH", "float", kPlPropGrid_MaxH } };
static const PlSchemaProp k_props_Input[] = { { "Value", "str", kPlPropInput_Value }, { "Placeholder", "str", kPlPropInput_Placeholder }, { "OnChange", "ptr", kPlPropInput_OnChange }, { "Disabled", "bool", kPlPropInput_Disabled }, { "Password", "bool", kPlPropInput_Password }, { "OnSubmit", "ptr", kPlPropInput_OnSubmit } };
static const PlSchemaProp k_props_TextArea[] = { { "Value", "str", kPlPropTextArea_Value }, { "Placeholder", "str", kPlPropTextArea_Placeholder }, { "OnChange", "ptr", kPlPropTextArea_OnChange }, { "Rows", "int", kPlPropTextArea_Rows }, { "Dir", "int", kPlPropTextArea_Dir }, { "Disabled", "bool", kPlPropTextArea_Disabled }, { "Cursor", "int", kPlPropTextArea_Cursor }, { "Anchor", "int", kPlPropTextArea_Anchor } };
static const PlSchemaProp k_props_Checkbox[] = { { "Checked", "bool", kPlPropCheckbox_Checked }, { "OnChange", "ptr", kPlPropCheckbox_OnChange }, { "Disabled", "bool", kPlPropCheckbox_Disabled } };
static const PlSchemaProp k_props_Switch[] = { { "On", "bool", kPlPropSwitch_On }, { "OnChange", "ptr", kPlPropSwitch_OnChange }, { "Disabled", "bool", kPlPropSwitch_Disabled } };
static const PlSchemaProp k_props_Slider[] = { { "Value", "float", kPlPropSlider_Value }, { "OnChange", "ptr", kPlPropSlider_OnChange }, { "Disabled", "bool", kPlPropSlider_Disabled } };
static const PlSchemaProp k_props_Select[] = { { "Value", "int", kPlPropSelect_Value }, { "OnChange", "ptr", kPlPropSelect_OnChange }, { "Placeholder", "str", kPlPropSelect_Placeholder }, { "Options", "ptr", kPlPropSelect_Options }, { "OptionCount", "int", kPlPropSelect_OptionCount }, { "Disabled", "bool", kPlPropSelect_Disabled } };
static const PlSchemaProp k_props_Progress[] = { { "Value", "float", kPlPropProgress_Value }, { "Thickness", "float", kPlPropProgress_Thickness } };
static const PlSchemaProp k_props_Modal[] = { { "Open", "bool", kPlPropModal_Open }, { "OnClose", "ptr", kPlPropModal_OnClose }, { "Child", "PlNode", kPlPropModal_Child } };
static const PlSchemaProp k_props_Tooltip[] = { { "Content", "str", kPlPropTooltip_Content }, { "Child", "PlNode", kPlPropTooltip_Child }, { "Delay", "float", kPlPropTooltip_Delay }, { "ChildNode", "ptr", kPlPropTooltip_ChildNode } };
static const PlSchemaProp k_props_Radio[] = { { "Checked", "bool", kPlPropRadio_Checked }, { "OnChange", "ptr", kPlPropRadio_OnChange }, { "Disabled", "bool", kPlPropRadio_Disabled } };
static const PlSchemaProp k_props_Badge[] = { { "Count", "int", kPlPropBadge_Count }, { "Content", "str", kPlPropBadge_Content }, { "Color", "PlColor", kPlPropBadge_Color }, { "ChildNode", "ptr", kPlPropBadge_ChildNode } };
static const PlSchemaProp k_props_Chip[] = { { "Label", "str", kPlPropChip_Label }, { "Selected", "bool", kPlPropChip_Selected }, { "OnTap", "ptr", kPlPropChip_OnTap }, { "OnRemove", "ptr", kPlPropChip_OnRemove }, { "Disabled", "bool", kPlPropChip_Disabled } };
static const PlSchemaProp k_props_Accordion[] = { { "Title", "str", kPlPropAccordion_Title }, { "Open", "bool", kPlPropAccordion_Open }, { "OnToggle", "ptr", kPlPropAccordion_OnToggle }, { "Child", "PlNode", kPlPropAccordion_Child }, { "ChildNode", "ptr", kPlPropAccordion_ChildNode } };
static const PlSchemaProp k_props_Tabs[] = { { "ActiveIndex", "int", kPlPropTabs_ActiveIndex }, { "OnChange", "ptr", kPlPropTabs_OnChange }, { "Labels", "ptr", kPlPropTabs_Labels }, { "Count", "int", kPlPropTabs_Count } };
static const PlSchemaProp k_props_Avatar[] = { { "Initials", "str", kPlPropAvatar_Initials }, { "Color", "PlColor", kPlPropAvatar_Color }, { "Size", "float", kPlPropAvatar_Size }, { "Src", "ptr", kPlPropAvatar_Src } };
static const PlSchemaProp k_props_List[] = { { "Count", "int", kPlPropList_Count }, { "ItemHeight", "float", kPlPropList_ItemHeight }, { "Builder", "ptr", kPlPropList_Builder }, { "ScrollY", "float", kPlPropList_ScrollY }, { "OnScroll", "ptr", kPlPropList_OnScroll }, { "Height", "float", kPlPropList_Height }, { "Width", "float", kPlPropList_Width } };
static const PlSchemaProp k_props_Notification[] = { { "Message", "str", kPlPropNotification_Message }, { "Duration", "float", kPlPropNotification_Duration }, { "Variant", "int", kPlPropNotification_Variant }, { "OnClose", "ptr", kPlPropNotification_OnClose }, { "Visible", "bool", kPlPropNotification_Visible } };
static const PlSchemaProp k_props_RichText[] = { { "Spans", "ptr", kPlPropRichText_Spans }, { "SpanCount", "int", kPlPropRichText_SpanCount }, { "Wrap", "bool", kPlPropRichText_Wrap } };
static const PlSchemaProp k_props_Menu[] = { { "Open", "bool", kPlPropMenu_Open }, { "Items", "ptr", kPlPropMenu_Items }, { "ItemCount", "int", kPlPropMenu_ItemCount }, { "OnSelect", "ptr", kPlPropMenu_OnSelect }, { "X", "float", kPlPropMenu_X }, { "Y", "float", kPlPropMenu_Y } };
static const PlSchemaProp k_props_Pagination[] = { { "Page", "int", kPlPropPagination_Page }, { "PageCount", "int", kPlPropPagination_PageCount }, { "OnChange", "ptr", kPlPropPagination_OnChange } };
static const PlSchemaProp k_props_ColorPicker[] = { { "Value", "PlColor", kPlPropColorPicker_Value }, { "OnChange", "ptr", kPlPropColorPicker_OnChange } };
static const PlSchemaProp k_props_DatePicker[] = { { "Year", "int", kPlPropDatePicker_Year }, { "Month", "int", kPlPropDatePicker_Month }, { "Day", "int", kPlPropDatePicker_Day }, { "OnChange", "ptr", kPlPropDatePicker_OnChange } };
static const PlSchemaProp k_props_Stepper[] = { { "Value", "int", kPlPropStepper_Value }, { "Min", "int", kPlPropStepper_Min }, { "Max", "int", kPlPropStepper_Max }, { "Step", "int", kPlPropStepper_Step }, { "OnChange", "ptr", kPlPropStepper_OnChange }, { "Disabled", "bool", kPlPropStepper_Disabled } };
static const PlSchemaProp k_props_Rating[] = { { "Value", "int", kPlPropRating_Value }, { "Max", "int", kPlPropRating_Max }, { "OnChange", "ptr", kPlPropRating_OnChange }, { "ReadOnly", "bool", kPlPropRating_ReadOnly } };
static const PlSchemaProp k_props_Timeline[] = { { "Items", "ptr", kPlPropTimeline_Items }, { "ItemCount", "int", kPlPropTimeline_ItemCount } };
static const PlSchemaProp k_props_Table[] = { { "Columns", "ptr", kPlPropTable_Columns }, { "ColumnCount", "int", kPlPropTable_ColumnCount }, { "Rows", "ptr", kPlPropTable_Rows }, { "RowCount", "int", kPlPropTable_RowCount }, { "OnRowSelect", "ptr", kPlPropTable_OnRowSelect }, { "SelectedRow", "int", kPlPropTable_SelectedRow } };
static const PlSchemaProp k_props_SplitPane[] = { { "Split", "float", kPlPropSplitPane_Split }, { "Vertical", "bool", kPlPropSplitPane_Vertical }, { "OnChange", "ptr", kPlPropSplitPane_OnChange }, { "First", "ptr", kPlPropSplitPane_First }, { "Second", "ptr", kPlPropSplitPane_Second }, { "Width", "float", kPlPropSplitPane_Width }, { "Height", "float", kPlPropSplitPane_Height } };
static const PlSchemaProp k_props_Carousel[] = { { "Index", "int", kPlPropCarousel_Index }, { "Count", "int", kPlPropCarousel_Count }, { "Builder", "ptr", kPlPropCarousel_Builder }, { "OnChange", "ptr", kPlPropCarousel_OnChange }, { "Width", "float", kPlPropCarousel_Width }, { "Height", "float", kPlPropCarousel_Height } };
static const PlSchemaProp k_props_SearchBar[] = { { "Value", "str", kPlPropSearchBar_Value }, { "Placeholder", "str", kPlPropSearchBar_Placeholder }, { "OnChange", "ptr", kPlPropSearchBar_OnChange }, { "OnSubmit", "ptr", kPlPropSearchBar_OnSubmit }, { "OnClear", "ptr", kPlPropSearchBar_OnClear } };
static const PlSchemaProp k_props_Breadcrumb[] = { { "Items", "ptr", kPlPropBreadcrumb_Items }, { "ItemCount", "int", kPlPropBreadcrumb_ItemCount }, { "OnClick", "ptr", kPlPropBreadcrumb_OnClick } };

static const PlSchemaWidget k_widgets[] = {
    { "pl.Box", k_props_Box, 4 },
    { "pl.Row", (const PlSchemaProp*)0, 0 },
    { "pl.Column", (const PlSchemaProp*)0, 0 },
    { "pl.Stack", (const PlSchemaProp*)0, 0 },
    { "pl.Portal", (const PlSchemaProp*)0, 0 },
    { "pl.Text", k_props_Text, 6 },
    { "pl.Image", k_props_Image, 2 },
    { "pl.Button", k_props_Button, 4 },
    { "pl.Spacer", (const PlSchemaProp*)0, 0 },
    { "pl.Divider", k_props_Divider, 1 },
    { "pl.Scroll", k_props_Scroll, 5 },
    { "pl.Grid", k_props_Grid, 6 },
    { "pl.Input", k_props_Input, 6 },
    { "pl.TextArea", k_props_TextArea, 8 },
    { "pl.Checkbox", k_props_Checkbox, 3 },
    { "pl.Switch", k_props_Switch, 3 },
    { "pl.Slider", k_props_Slider, 3 },
    { "pl.Select", k_props_Select, 6 },
    { "pl.Progress", k_props_Progress, 2 },
    { "pl.Modal", k_props_Modal, 3 },
    { "pl.Tooltip", k_props_Tooltip, 4 },
    { "pl.Radio", k_props_Radio, 3 },
    { "pl.Badge", k_props_Badge, 4 },
    { "pl.Chip", k_props_Chip, 5 },
    { "pl.Accordion", k_props_Accordion, 5 },
    { "pl.Tabs", k_props_Tabs, 4 },
    { "pl.Avatar", k_props_Avatar, 4 },
    { "pl.List", k_props_List, 7 },
    { "pl.Notification", k_props_Notification, 5 },
    { "pl.RichText", k_props_RichText, 3 },
    { "pl.Menu", k_props_Menu, 6 },
    { "pl.Pagination", k_props_Pagination, 3 },
    { "pl.ColorPicker", k_props_ColorPicker, 2 },
    { "pl.DatePicker", k_props_DatePicker, 4 },
    { "pl.Stepper", k_props_Stepper, 6 },
    { "pl.Rating", k_props_Rating, 4 },
    { "pl.Timeline", k_props_Timeline, 2 },
    { "pl.Table", k_props_Table, 6 },
    { "pl.SplitPane", k_props_SplitPane, 7 },
    { "pl.Carousel", k_props_Carousel, 6 },
    { "pl.SearchBar", k_props_SearchBar, 5 },
    { "pl.Breadcrumb", k_props_Breadcrumb, 3 },
};

const PlSchemaWidget* pl_schema_table(int* n_out) {
    if (n_out) *n_out = (int)(sizeof k_widgets / sizeof k_widgets[0]);
    return k_widgets;
}
