/* ============================================================================
 * GENERATED by tools/gen_schema.py from schema/plume.schema.json —— 请勿手改。
 * 改动改 schema 后重跑生成器；CTest `schema_gen_drift` 会校验产物与 schema 一致。
 * ==========================================================================*/
#ifndef PLUME_UI_GEN_H
#define PLUME_UI_GEN_H
#include <plume/plume_kernel.h>
#ifndef PL_GEN_MAX_CHILDREN
#define PL_GEN_MAX_CHILDREN 16
#endif
/* schema 生成的 L1 typed desc + 构造器 + L2 宏（人体工学构建层）。字段未设(0)→用控件默认。*/

/* ---- pl.Box（schema 生成的 L1）---- */
typedef struct {
    float          width;   /* 0=未设(自动按内容) */
    float          height;   /* 0=未设(自动按内容) */
    float          min_width;   /* 尺寸边界；0=未设 */
    float          min_height;   /* 尺寸边界；0=未设 */
    float          max_width;   /* 尺寸边界；0=未设 */
    float          max_height;   /* 尺寸边界；0=未设 */
    PlColor        bg;   /* 0xRRGGBBAA；0=未设(透明) */
    float          radius;   /* 0=未设(直角) */
    bool           clip;   /* 裁剪溢出子(含圆角)；默认 false */
    float          padding;   /* 统一内边距；0=未设(无) */
    PlColor        border_color;   /* 边框色（仅 border_width 设时生效） */
    float          border_width;   /* 0=未设(无边框) */
    float          opacity;   /* 0=未设(=1) */
    float          grow;   /* flex 主轴 grow；0=未设 */
    float          shrink;   /* flex 主轴 shrink；0=未设(不收缩) */
    PlHandler      on_tap;   /* 点击处理器；NULL=无 */
    PlNode         child;   /* 可选单子 */
} PlBoxDesc;
PlNode pl_box(PlCtx ctx, PlBoxDesc d);
#define PL_BOX(ctx, ...) pl_box((ctx), (PlBoxDesc){ __VA_ARGS__ })

/* ---- pl.Row（schema 生成的 L1）---- */
typedef struct {
    float          gap;   /* 项目间距；0=未设(默认 8) */
    int            justify;   /* 主轴对齐 kPlJustify_* */
    int            align;   /* 交叉轴对齐 kPlAlign_* */
    PlNode children[PL_GEN_MAX_CHILDREN];   /* 子项（顺序填，遇 NULL 止） */
} PlRowDesc;
PlNode pl_row(PlCtx ctx, PlRowDesc d);
#define PL_ROW(ctx, ...) pl_row((ctx), (PlRowDesc){ __VA_ARGS__ })

/* ---- pl.Column（schema 生成的 L1）---- */
typedef struct {
    float          gap;   /* 项目间距；0=未设(默认 12) */
    int            justify;   /* 主轴对齐 kPlJustify_* */
    int            align;   /* 交叉轴对齐 kPlAlign_* */
    PlNode children[PL_GEN_MAX_CHILDREN];   /* 子项（顺序填，遇 NULL 止） */
} PlColumnDesc;
PlNode pl_column(PlCtx ctx, PlColumnDesc d);
#define PL_COLUMN(ctx, ...) pl_column((ctx), (PlColumnDesc){ __VA_ARGS__ })

/* ---- pl.Stack（schema 生成的 L1）---- */
typedef struct {
    float          width;   /* 0=未设(子最大) */
    float          height;   /* 0=未设(子最大) */
    int            justify;   /* 水平对齐 kPlJustify_Start/Center/End */
    int            align;   /* 竖直对齐 kPlAlign_Start/Center/End */
    PlNode children[PL_GEN_MAX_CHILDREN];   /* 子项（先者在底，遇 NULL 止） */
} PlStackDesc;
PlNode pl_stack(PlCtx ctx, PlStackDesc d);
#define PL_STACK(ctx, ...) pl_stack((ctx), (PlStackDesc){ __VA_ARGS__ })

/* ---- pl.Portal（schema 生成的 L1）---- */
typedef struct {
    float          x;   /* 放置 x（根坐标；anchor 时为相对容器偏移）；0=左上/原位 */
    float          y;   /* 放置 y（根坐标；anchor 时为相对容器偏移）；0=左上/原位 */
    int            z;   /* 层叠序（大者在上）；0=默认 */
    bool           anchor;   /* 锚定：x/y 改作相对偏移，基准=portal 所在容器布局后位置（浮层随触发处移动） */
    bool           flip;   /* 边界翻转（仅锚定）：默认下方会溢出视口底边且上方放得下时，自动翻到触发处上方 */
    PlNode         child;   /* 浮层内容 */
} PlPortalDesc;
PlNode pl_portal(PlCtx ctx, PlPortalDesc d);
#define PL_PORTAL(ctx, ...) pl_portal((ctx), (PlPortalDesc){ __VA_ARGS__ })

/* ---- pl.Text（schema 生成的 L1）---- */
typedef struct {
    const char*    text;   /* 文本（拷贝） */
    float          size;   /* 字号；0=未设(16) */
    PlColor        color;   /* 0xRRGGBBAA 或 pl_hex；0=未设(黑) */
    float          grow;   /* flex grow */
    bool           ellipsis;   /* 放不下尾部省略号 */
    bool           wrap;   /* 超宽按词换行 */
    int            dir;   /* 文本方向 kPlDir_Auto/LTR/RTL */
} PlTextDesc;
PlNode pl_text(PlCtx ctx, PlTextDesc d);
#define PL_TEXT(ctx, ...) pl_text((ctx), (PlTextDesc){ __VA_ARGS__ })

/* ---- pl.Image（schema 生成的 L1）---- */
typedef struct {
    CevgImage*     src;   /* 图像（宿主持有生命周期） */
    float          width;   /* 0=未设(图像自然尺寸) */
    float          height;   /* 0=未设(图像自然尺寸) */
    float          radius;   /* 圆角裁剪；0=未设(方角) */
    float          grow;   /* flex grow */
} PlImageDesc;
PlNode pl_image(PlCtx ctx, PlImageDesc d);
#define PL_IMAGE(ctx, ...) pl_image((ctx), (PlImageDesc){ __VA_ARGS__ })

/* ---- pl.Button（schema 生成的 L1）---- */
typedef struct {
    const char*    label;   /* 按钮文字 */
    PlColor        bg;   /* 底色；0=未设(默认蓝) */
    PlColor        color;   /* 文字色；0=未设(默认白) */
    float          radius;   /* 圆角；0=未设(10) */
    float          width;   /* 0=未设(按内容) */
    float          height;   /* 0=未设(按内容) */
    float          font_size;   /* 0=未设(20) */
    PlHandler      on_press;   /* 点击动作 */
} PlButtonDesc;
PlNode pl_button(PlCtx ctx, PlButtonDesc d);
#define PL_BUTTON(ctx, ...) pl_button((ctx), (PlButtonDesc){ __VA_ARGS__ })

/* ---- pl.Spacer（schema 生成的 L1，无 desc）---- */
PlNode pl_spacer(PlCtx ctx);
#define PL_SPACER(ctx) pl_spacer((ctx))

/* ---- pl.Divider（schema 生成的 L1）---- */
typedef struct {
    PlColor        color;   /* 线色；0=未设(浅灰) */
    float          thickness;   /* 厚度；0=未设(1) */
    bool           vertical;   /* 竖向（填高×厚） */
} PlDividerDesc;
PlNode pl_divider(PlCtx ctx, PlDividerDesc d);
#define PL_DIVIDER(ctx, ...) pl_divider((ctx), (PlDividerDesc){ __VA_ARGS__ })

/* ---- pl.Scroll（schema 生成的 L1）---- */
typedef struct {
    float          width;   /* 视口宽；0=未设(按约束) */
    float          height;   /* 视口高；0=未设(按约束) */
    float          scroll;   /* 竖直滚动偏移（内容上移量） */
    float          scroll_x;   /* 水平滚动偏移（内容左移量）；0=未设 */
    bool           scrollbar;   /* 显示滚动条指示器（双轴：内容溢出哪轴显哪轴） */
    PlNode         child;   /* 内容（可比视口高） */
} PlScrollDesc;
PlNode pl_scroll(PlCtx ctx, PlScrollDesc d);
#define PL_SCROLL(ctx, ...) pl_scroll((ctx), (PlScrollDesc){ __VA_ARGS__ })

/* ---- pl.Grid（schema 生成的 L1）---- */
typedef struct {
    int            cols;   /* 列数；0=未设(默认 2) */
    float          gap;   /* 项目间距；0=未设 */
    int            autofit;   /* 列宽按内容自适应；0=未设(等宽) */
    float          min_w;   /* 自适应时每列最小宽 */
    float          max_w;   /* 自适应时每列最大宽(0=不封顶) */
    float          min_h;   /* 每行最小高(0=不保底) */
    float          max_h;   /* 每行最大高(0=不封顶) */
    PlNode children[PL_GEN_MAX_CHILDREN];   /* 子项（顺序填，遇 NULL 止） */
} PlGridDesc;
PlNode pl_grid(PlCtx ctx, PlGridDesc d);
#define PL_GRID(ctx, ...) pl_grid((ctx), (PlGridDesc){ __VA_ARGS__ })

/* ---- pl.Input（schema 生成的 L1）---- */
typedef struct {
    const char*    value;   /* 当前值（受控）；NULL=无 */
    const char*    placeholder;   /* 空值时的占位文字 */
    PlHandler      on_change;   /* 值变化回调；pl_event_text=新值 */
    PlHandler      on_submit;   /* Enter 提交回调 */
    bool           disabled;   /* 禁用态 */
    bool           password;   /* 密码模式（• 遮盖） */
    float          width;   /* 0=未设(自动) */
    float          height;   /* 0=未设(自动) */
} PlInputDesc;
PlNode pl_input(PlCtx ctx, PlInputDesc d);
#define PL_INPUT(ctx, ...) pl_input((ctx), (PlInputDesc){ __VA_ARGS__ })

/* ---- pl.TextArea（schema 生成的 L1）---- */
typedef struct {
    const char*    value;   /* 当前值（受控，可含 \n）；NULL=无 */
    const char*    placeholder;   /* 空值时的占位文字 */
    PlHandler      on_change;   /* 值变化回调；pl_event_text=新值 */
    int            rows;   /* 可见行数（决定默认高度）；0=未设(4) */
    int            dir;   /* 文本方向 kPlDir_Auto/LTR/RTL */
    bool           disabled;   /* 禁用态 */
    float          width;   /* 0=未设(自动) */
    float          height;   /* 0=未设(按 rows) */
} PlTextAreaDesc;
PlNode pl_textarea(PlCtx ctx, PlTextAreaDesc d);
#define PL_TEXTAREA(ctx, ...) pl_textarea((ctx), (PlTextAreaDesc){ __VA_ARGS__ })

/* ---- pl.Checkbox（schema 生成的 L1）---- */
typedef struct {
    bool           checked;   /* 勾选状态 */
    PlHandler      on_change;   /* 切换回调；pl_event_text=\"1\"/\"0\" */
    bool           disabled;   /* 禁用态 */
} PlCheckboxDesc;
PlNode pl_checkbox(PlCtx ctx, PlCheckboxDesc d);
#define PL_CHECKBOX(ctx, ...) pl_checkbox((ctx), (PlCheckboxDesc){ __VA_ARGS__ })

/* ---- pl.Switch（schema 生成的 L1）---- */
typedef struct {
    bool           on;   /* 开关状态 */
    PlHandler      on_change;   /* 切换回调；pl_event_text=\"1\"/\"0\" */
    bool           disabled;   /* 禁用态 */
} PlSwitchDesc;
PlNode pl_switch(PlCtx ctx, PlSwitchDesc d);
#define PL_SWITCH(ctx, ...) pl_switch((ctx), (PlSwitchDesc){ __VA_ARGS__ })

/* ---- pl.Slider（schema 生成的 L1）---- */
typedef struct {
    float          value;   /* 当前值 0.0–1.0 */
    PlHandler      on_change;   /* 拖动回调；pl_event_text=\"0.0000\"–\"1.0000\" */
    bool           disabled;   /* 禁用态 */
} PlSliderDesc;
PlNode pl_slider(PlCtx ctx, PlSliderDesc d);
#define PL_SLIDER(ctx, ...) pl_slider((ctx), (PlSliderDesc){ __VA_ARGS__ })

/* ---- pl.Select（schema 生成的 L1）---- */
typedef struct {
    int            value;   /* 选中项索引（-1=未选） */
    const char*    placeholder;   /* 未选中时的提示文字 */
    PlHandler      on_change;   /* 选中变化回调 */
    void*          options;   /* const char** */
    int            option_count;   /* 选项数 */
    bool           disabled;   /* 禁用 */
} PlSelectDesc;
PlNode pl_select(PlCtx ctx, PlSelectDesc d);
#define PL_SELECT(ctx, ...) pl_select((ctx), (PlSelectDesc){ __VA_ARGS__ })

/* ---- pl.Progress（schema 生成的 L1）---- */
typedef struct {
    float          value;   /* 0.0–1.0；< 0 = spinner */
    float          thickness;   /* 0=默认 6px */
    float          width;   /* 0=自动 */
} PlProgressDesc;
PlNode pl_progress(PlCtx ctx, PlProgressDesc d);
#define PL_PROGRESS(ctx, ...) pl_progress((ctx), (PlProgressDesc){ __VA_ARGS__ })

/* ---- pl.Modal（schema 生成的 L1）---- */
typedef struct {
    bool           open;   /* 是否显示 */
    PlHandler      on_close;   /* 关闭回调 */
    PlNode         child;   /* 内容 */
} PlModalDesc;
PlNode pl_modal(PlCtx ctx, PlModalDesc d);
#define PL_MODAL(ctx, ...) pl_modal((ctx), (PlModalDesc){ __VA_ARGS__ })

/* ---- pl.Tooltip（schema 生成的 L1）---- */
typedef struct {
    const char*    content;   /* 提示文字 */
    float          delay;   /* 0=默认 0.3s */
    PlNode         child;   /* 触发元素 */
} PlTooltipDesc;
PlNode pl_tooltip(PlCtx ctx, PlTooltipDesc d);
#define PL_TOOLTIP(ctx, ...) pl_tooltip((ctx), (PlTooltipDesc){ __VA_ARGS__ })

/* ---- pl.Radio（schema 生成的 L1）---- */
typedef struct {
    bool           checked;   /* 选中 */
    PlHandler      on_change;   /* 点击回调 */
    bool           disabled;   /* 禁用 */
} PlRadioDesc;
PlNode pl_radio(PlCtx ctx, PlRadioDesc d);
#define PL_RADIO(ctx, ...) pl_radio((ctx), (PlRadioDesc){ __VA_ARGS__ })

/* ---- pl.Badge（schema 生成的 L1）---- */
typedef struct {
    int            count;   /* 数字；0=隐藏 */
    const char*    content;   /* 文字（优先） */
    PlColor        color;   /* 0=红 */
    PlNode         child;   /* 被标注的内容 */
} PlBadgeDesc;
PlNode pl_badge(PlCtx ctx, PlBadgeDesc d);
#define PL_BADGE(ctx, ...) pl_badge((ctx), (PlBadgeDesc){ __VA_ARGS__ })

/* ---- pl.Chip（schema 生成的 L1）---- */
typedef struct {
    const char*    label;   /* 文字 */
    bool           selected;   /* 选中高亮 */
    PlHandler      on_tap;   /* 点击 */
    PlHandler      on_remove;   /* 删除（NULL=不显示×） */
    bool           disabled;   /* 禁用 */
} PlChipDesc;
PlNode pl_chip(PlCtx ctx, PlChipDesc d);
#define PL_CHIP(ctx, ...) pl_chip((ctx), (PlChipDesc){ __VA_ARGS__ })

/* ---- pl.Accordion（schema 生成的 L1）---- */
typedef struct {
    const char*    title;   /* 标题 */
    bool           open;   /* 展开 */
    PlHandler      on_toggle;   /* 点击标题 */
    PlNode         child;   /* 折叠内容 */
} PlAccordionDesc;
PlNode pl_accordion(PlCtx ctx, PlAccordionDesc d);
#define PL_ACCORDION(ctx, ...) pl_accordion((ctx), (PlAccordionDesc){ __VA_ARGS__ })

/* ---- pl.Tabs（schema 生成的 L1）---- */
typedef struct {
    int            active_index;   /* 激活索引 */
    PlHandler      on_change;   /* 切换回调 */
    void*          labels;   /* const char** */
    int            count;   /* 标签数 */
} PlTabsDesc;
PlNode pl_tabs(PlCtx ctx, PlTabsDesc d);
#define PL_TABS(ctx, ...) pl_tabs((ctx), (PlTabsDesc){ __VA_ARGS__ })

/* ---- pl.Avatar（schema 生成的 L1）---- */
typedef struct {
    const char*    initials;   /* 首字母 */
    PlColor        color;   /* 0=自动 */
    float          size;   /* 直径 px */
    void*          src;   /* CevgImage* */
} PlAvatarDesc;
PlNode pl_avatar(PlCtx ctx, PlAvatarDesc d);
#define PL_AVATAR(ctx, ...) pl_avatar((ctx), (PlAvatarDesc){ __VA_ARGS__ })

/* ---- pl.List（schema 生成的 L1）---- */
typedef struct {
    int            count;   /* 总项数 */
    float          item_height;   /* 等高 px */
    void*          builder;   /* PlListBuilder */
    float          scroll_y;   /* 滚动偏移 */
    void*          on_scroll;   /* 滚动回调 */
    float          height;   /* 视口高 */
    float          width;   /* 视口宽 */
} PlListDesc;
PlNode pl_list(PlCtx ctx, PlListDesc d);
#define PL_LIST(ctx, ...) pl_list((ctx), (PlListDesc){ __VA_ARGS__ })

/* ---- pl.Notification（schema 生成的 L1）---- */
typedef struct {
    const char*    message;   /* 消息文字 */
    float          duration;   /* 秒；0=不自动消 */
    int            variant;   /* 0=Info 1=Success 2=Warn 3=Error */
    PlHandler      on_close;   /* 消失回调 */
    bool           visible;   /* 是否显示 */
} PlNotificationDesc;
PlNode pl_notification(PlCtx ctx, PlNotificationDesc d);
#define PL_NOTIFICATION(ctx, ...) pl_notification((ctx), (PlNotificationDesc){ __VA_ARGS__ })

/* ---- pl.RichText（schema 生成的 L1）---- */
typedef struct {
    void*          spans;   /* PlSpan* */
    int            span_count;   /* 数量 */
    bool           wrap;   /* 换行 */
} PlRichTextDesc;
PlNode pl_richtext(PlCtx ctx, PlRichTextDesc d);
#define PL_RICHTEXT(ctx, ...) pl_richtext((ctx), (PlRichTextDesc){ __VA_ARGS__ })

/* ---- pl.Menu（schema 生成的 L1）---- */
typedef struct {
    bool           open;   /* 展开 */
    void*          items;   /* PlMenuItem* */
    int            item_count;   /* 数量 */
    PlHandler      on_select;   /* 选中回调 */
    float          x;   /* 弹出 x */
    float          y;   /* 弹出 y */
} PlMenuDesc;
PlNode pl_menu(PlCtx ctx, PlMenuDesc d);
#define PL_MENU(ctx, ...) pl_menu((ctx), (PlMenuDesc){ __VA_ARGS__ })

/* ---- pl.Pagination（schema 生成的 L1）---- */
typedef struct {
    int            page;   /* 当前页 */
    int            page_count;   /* 总页数 */
    PlHandler      on_change;   /* 切换回调 */
} PlPaginationDesc;
PlNode pl_pagination(PlCtx ctx, PlPaginationDesc d);
#define PL_PAGINATION(ctx, ...) pl_pagination((ctx), (PlPaginationDesc){ __VA_ARGS__ })

/* ---- pl.ColorPicker（schema 生成的 L1）---- */
typedef struct {
    PlColor        value;   /* 颜色 */
    PlHandler      on_change;   /* 回调 */
} PlColorPickerDesc;
PlNode pl_colorpicker(PlCtx ctx, PlColorPickerDesc d);
#define PL_COLORPICKER(ctx, ...) pl_colorpicker((ctx), (PlColorPickerDesc){ __VA_ARGS__ })

/* ---- pl.DatePicker（schema 生成的 L1）---- */
typedef struct {
    int            year;   /* 年 */
    int            month;   /* 月 1-12 */
    int            day;   /* 日 1-31 */
    PlHandler      on_change;   /* 回调 */
} PlDatePickerDesc;
PlNode pl_datepicker(PlCtx ctx, PlDatePickerDesc d);
#define PL_DATEPICKER(ctx, ...) pl_datepicker((ctx), (PlDatePickerDesc){ __VA_ARGS__ })

/* ---- pl.Stepper（schema 生成的 L1）---- */
typedef struct {
    int            value;   /* 当前值 */
    int            min;   /* 最小值 */
    int            max;   /* 最大值 */
    int            step;   /* 步进量 */
    PlHandler      on_change;   /* 回调 */
    bool           disabled;   /* 禁用 */
} PlStepperDesc;
PlNode pl_stepper(PlCtx ctx, PlStepperDesc d);
#define PL_STEPPER(ctx, ...) pl_stepper((ctx), (PlStepperDesc){ __VA_ARGS__ })

/* ---- pl.Rating（schema 生成的 L1）---- */
typedef struct {
    int            value;   /* 评分 0-5 */
    int            max;   /* 最大星数 */
    PlHandler      on_change;   /* 回调 */
    bool           read_only;   /* 只读 */
} PlRatingDesc;
PlNode pl_rating(PlCtx ctx, PlRatingDesc d);
#define PL_RATING(ctx, ...) pl_rating((ctx), (PlRatingDesc){ __VA_ARGS__ })

/* ---- pl.Timeline（schema 生成的 L1）---- */
typedef struct {
    void*          items;   /* PlTimelineItem* */
    int            item_count;   /* 数量 */
} PlTimelineDesc;
PlNode pl_timeline(PlCtx ctx, PlTimelineDesc d);
#define PL_TIMELINE(ctx, ...) pl_timeline((ctx), (PlTimelineDesc){ __VA_ARGS__ })

/* ---- pl.Table（schema 生成的 L1）---- */
typedef struct {
    void*          columns;   /* PlTableColumn* */
    int            column_count;   /* 列数 */
    void*          rows;   /* const char** */
    int            row_count;   /* 行数 */
    void*          on_row_select;   /* 回调 */
    int            selected_row;   /* 选中行 */
} PlTableDesc;
PlNode pl_table(PlCtx ctx, PlTableDesc d);
#define PL_TABLE(ctx, ...) pl_table((ctx), (PlTableDesc){ __VA_ARGS__ })

/* ---- pl.SplitPane（schema 生成的 L1）---- */
typedef struct {
    float          split;   /* 比例 0-1 */
    bool           vertical;   /* 左右分割 */
    PlHandler      on_change;   /* 回调 */
    void*          first;   /* 第一面板 */
    void*          second;   /* 第二面板 */
    float          width;   /* 总宽 */
    float          height;   /* 总高 */
} PlSplitPaneDesc;
PlNode pl_splitpane(PlCtx ctx, PlSplitPaneDesc d);
#define PL_SPLITPANE(ctx, ...) pl_splitpane((ctx), (PlSplitPaneDesc){ __VA_ARGS__ })

/* ---- pl.Carousel（schema 生成的 L1）---- */
typedef struct {
    int            index;   /* 当前项 */
    int            count;   /* 总数 */
    void*          builder;   /* PlListBuilder */
    PlHandler      on_change;   /* 切换回调 */
    float          width;   /* 项宽 px */
    float          height;   /* 高度 px */
} PlCarouselDesc;
PlNode pl_carousel(PlCtx ctx, PlCarouselDesc d);
#define PL_CAROUSEL(ctx, ...) pl_carousel((ctx), (PlCarouselDesc){ __VA_ARGS__ })

/* ---- pl.SearchBar（schema 生成的 L1）---- */
typedef struct {
    const char*    value;   /* 当前文字 */
    const char*    placeholder;   /* 提示文字 */
    PlHandler      on_change;   /* 变更回调 */
    PlHandler      on_submit;   /* 提交回调 */
    PlHandler      on_clear;   /* 清除回调 */
} PlSearchBarDesc;
PlNode pl_searchbar(PlCtx ctx, PlSearchBarDesc d);
#define PL_SEARCHBAR(ctx, ...) pl_searchbar((ctx), (PlSearchBarDesc){ __VA_ARGS__ })

/* ---- pl.Breadcrumb（schema 生成的 L1）---- */
typedef struct {
    void*          items;   /* const char** */
    int            item_count;   /* 数量 */
    void*          on_click;   /* 点击回调 */
} PlBreadcrumbDesc;
PlNode pl_breadcrumb(PlCtx ctx, PlBreadcrumbDesc d);
#define PL_BREADCRUMB(ctx, ...) pl_breadcrumb((ctx), (PlBreadcrumbDesc){ __VA_ARGS__ })

#endif /* PLUME_UI_GEN_H */
